services:
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    container_name: fraud_api
    ports:
      - "8000:8000"
    environment:
      - ARTIFACTS_DIR=artifacts
    # If your API needs the trained artifacts, ensure they exist in the image OR mount them:
    volumes:
      - ./artifacts:/app/artifacts
      - ./models:/app/models
      - ./reports:/app/reports
      - ./dataset:/app/dataset

  streamlit:
    build:
      context: .
      dockerfile: dockerfile.streamlit
    container_name: fraud_ui
    environment:
      # Compose DNS lets you call the api container by service name "api"
      - API_URL=http://api:8000/predict
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./artifacts:/app/artifacts
      - ./models:/app/models
      - ./reports:/app/reports
      - ./dataset:/app/dataset
  prometheus:
    image: prom/prometheus:latest
    container_name: fraud_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--web.route-prefix=/prometheus"
    - "--web.external-url=https://roykeanesyangu.com/prometheus"
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: fraud_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
       - GF_SERVER_ROOT_URL=https://roykeanesyangu.com/grafana/
       - GF_SERVER_SERVE_FROM_SUB_PATH=true

    depends_on:
      - prometheus

volumes:
  grafana_data: